#!/bin/sh

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    configure)
    mkdir -p /etc/prometheus-mac-proxy
    if ! getent group prometheus-mac-proxy >/dev/null; then
      addgroup --quiet --system prometheus-mac-proxy
    fi

    if ! getent passwd prometheus-mac-proxy >/dev/null; then
      adduser --quiet --system --ingroup prometheus-mac-proxy --shell /usr/sbin/nologin prometheus-mac-proxy
    fi

      systemctl daemon-reload
      systemctl enable --now prometheus-mac-proxy.service
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
